# House Price Prediction

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Dataset Loading: 
- Load the dataset into a Pandas DataFrame
- Display the first 10 rows

In [2]:
df = pd.read_csv('HousePricePrediction.csv')

print("First 10 rows:")
display(df.head(10))

First 10 rows:

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
5,5,50,RL,14115,Inside,1Fam,5,1993,1995,VinylSd,0.0,796.0,143000.0
6,6,20,RL,10084,Inside,1Fam,5,2004,2005,VinylSd,0.0,1686.0,307000.0
7,7,60,RL,10382,Corner,1Fam,6,1973,1973,HdBoard,32.0,1107.0,200000.0
8,8,50,RM,6120,Inside,1Fam,5,1931,1950,BrkFace,0.0,952.0,129900.0
9,9,190,RL,7420,Corner,2fmCon,6,1939,1950,MetalSd,0.0,991.0,118000.0

## Data Exploration: 
- Display the shape of the dataset
- Check data types of all columns
- Generate summary statistics of numerical features

In [3]:
print("Dataset Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nStatistical Summary:\n")
display(df.describe())

Dataset Shape: (2919, 13)

Data Types:
 Id                int64
MSSubClass        int64
MSZoning         object
LotArea           int64
LotConfig        object
BldgType         object
OverallCond       int64
YearBuilt         int64
YearRemodAdd      int64
Exterior1st      object
BsmtFinSF2      float64
TotalBsmtSF     float64
SalePrice       float64
dtype: object

Statistical Summary:

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

## Data Cleaning: 
- Identify missing values
- Handle missing values appropriately
- Check and remove duplicate records if any

In [4]:
print("Missing Values:\n",df.isna().sum())

Missing Values:
 Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [5]:
# Fill categorical missing values
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [6]:
# Fill numerical missing values
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [7]:
# Remove duplicates
df = df.drop_duplicates()
print("After Cleaning Missing Values:\n",df.isna().sum())

After Cleaning Missing Values:
 Id              0
MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

## Feature Selection: 
- Identify relevant features for analysis
- Remove unnecessary columns such as identifiers (e.g., Id)

In [8]:
print("All Features:\n", df.columns)

All Features:
 Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'LotConfig', 'BldgType',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'Exterior1st', 'BsmtFinSF2',
       'TotalBsmtSF', 'SalePrice'],
      dtype='object')

In [9]:
df = df.drop('Id', axis=1)

In [10]:
print("Remaining Features:\n", df.columns)

Remaining Features:
 Index(['MSSubClass', 'MSZoning', 'LotArea', 'LotConfig', 'BldgType',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'Exterior1st', 'BsmtFinSF2',
       'TotalBsmtSF', 'SalePrice'],
      dtype='object')

## Data Preprocessing: 
- Convert categorical variables into numerical form (encoding)
- Preparing the dataset for machine learning and display it’s preview in the output

In [11]:
df_encoded = pd.get_dummies(df, drop_first=True)

print("Encoded Dataset Preview:")
display(df_encoded.head())

Encoded Dataset Preview:

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.0,False,False,...,False,False,False,False,False,False,False,True,False,False
1,20,9600,8,1976,1976,0.0,1262.0,181500.0,False,False,...,False,False,False,True,False,False,False,False,False,False
2,60,11250,5,2001,2002,0.0,920.0,223500.0,False,False,...,False,False,False,False,False,False,False,True,False,False
3,70,9550,5,1915,1970,0.0,756.0,140000.0,False,False,...,False,False,False,False,False,False,False,False,True,False
4,60,14260,5,2000,2000,0.0,1145.0,250000.0,False,False,...,False,False,False,False,False,False,False,True,False,False

## Train-Test Split: 
- Split the dataset into training and testing sets
- Use an appropriate ratio (e.g., 80% training, 20% testing)

In [12]:
X = df_encoded.drop('SalePrice', axis=1)
y = df_encoded['SalePrice']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (2335, 33)
Testing set shape: (584, 33)

## Model Training: 
- Train a Linear Regression model using the training data

In [15]:
model = LinearRegression()

In [16]:
model.fit(X_train, y_train)

LinearRegression()

## Model Prediction: 
- Use the trained model to predict house prices on the test data

In [17]:
y_pred = model.predict(X_test)

In [ ]:
## Model Evaluation:
- Mean Absolute Error (MAE)
- Mean Squared Error (MSE)
- Root Mean Squared Error (RMSE)
- R² Score

In [18]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Model Performance:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

Model Performance:
MAE: 32042.044926488677
MSE: 2441285770.7271843
RMSE: 49409.36926056822
R2 Score: 0.33718696204142484

## Interpretation:
- Analyze the performance of the model
- Discuss whether the model is accurate or needs improvement

In [29]:
print("Model Interpretation:\n\nThe Linear Regression model was trained on the cleaned dataset.\nMAE represents average absolute error in predictions.\nMSE and RMSE measure overall prediction error magnitude.\nR2 Score shows how well the model explains variance in target variable.\n\nIf R2 is closer to 1, model performance is good.\nIf R2 is low, model may need feature engineering or better algorithms.")

Model Interpretation:

The Linear Regression model was trained on the cleaned dataset.
MAE represents average absolute error in predictions.
MSE and RMSE measure overall prediction error magnitude.
R2 Score shows how well the model explains variance in target variable.

If R2 is closer to 1, model performance is good.
If R2 is low, model may need feature engineering or better algorithms.